"Basic configuration
"================================================
set nocompatible
syntax on
let mapleader=","
set backspace=2
set laststatus=2
set history=500
set ruler
set number
set background=dark
set t_Co=256
if !has('gui_running')
	colorscheme tir_black
else
	"colorscheme ir_dark
	"colorscheme pablo
	"colorscheme brookstream
	"colorscheme stingray
	"colorscheme maroloccio3
	"colorscheme solarized
	colorscheme tron
	"colorscheme nefertiti
	"colorscheme mustang
endif

"Indentation settings
"================================================
set tabstop=4
set shiftwidth=4
"set expandtab
"set softtabstop=4
"set noexpandtab
"set cindent
"set autoindent
set smarttab
filetype plugin indent on
set foldmethod=syntax
set foldnestmax=10
set nofoldenable
set foldlevel=2

"Search settings
"================================================
set showmatch
set ignorecase
set smartcase
set incsearch
set hlsearch
nmap <silent> <leader>q :nohlsearch<CR>

"Extra key bindings
"================================================
nmap j gj
nmap k gk
"nmap <leader>p :CtrlP<CR>
"nmap <leader>a :Ack<Space>
nmap <C-j> <C-W>j
nmap <C-k> <C-W>k
nmap <C-h> <C-W>h
nmap <C-l> <C-W>l
imap <Esc> <C-c>

"GUI settings
"================================================
set guioptions-=m
set guioptions-=T
set guioptions-=r
set guioptions-=L
set guifont=Terminus\ 9

"Syntax highlighting (for strange extensions)
"================================================
au BufRead,BufNewFile *.sage set filetype=python
au BufRead,BufNewFile *.adoc set filetype=asciidoc
au BufRead,BufNewFile *bashrc* set filetype=sh

execute pathogen#infect()
